[workspace]
members = [ "members/dummy", "members/orphan",
	"members/ptrace_someone",
	"members/sigtrap_handle",
	"members/sigtrap_send",
]

[workspace.dependencies]
nix = { version = "0.29.0", features = ["signal", "ptrace", "process"] }
